version: '3.5'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: yii-app-services
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app:cached
    depends_on:
      - mysql
    networks:
      - yii-network

  nginx:
    image: nginx:1.19.8-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./src:/app:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl:cached
      - ./docker/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - yii-network

  mysql:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: study
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - yii-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8181:80
    networks:
      - yii-network

networks:
  yii-network:
    name: yii-network
    driver: bridge
